"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ClipboardCheck, Download, MapPin, Play, X } from "lucide-react";
import { collectionPlanCsv, getCollectionTasks } from "@/lib/collection-tasks";
import { COUNTRIES, type CollectionTask } from "@/lib/types";
import { useWorkspace } from "./workspace";

const priorityRank = { high: 3, medium: 2, low: 1 };
function download(tasks: CollectionTask[]) { const blob = new Blob([collectionPlanCsv(tasks)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "fieldloss-collection-plan.csv"; link.click(); URL.revokeObjectURL(url); }

export function CollectionTasksScreen() {
  const { state, ready, setCollectionTaskStatus } = useWorkspace(); const [country, setCountry] = useState<"FJ" | "AU">("FJ"); const [showDismissed, setShowDismissed] = useState(false);
  const tasks = useMemo(() => getCollectionTasks(state, country), [state, country]); const active = tasks.filter((task) => task.status !== "satisfied" && (showDismissed || task.status !== "dismissed")); const review = active.filter((task) => task.category === "review").sort((a, b) => priorityRank[b.priority] - priorityRank[a.priority]); const collect = active.filter((task) => task.category === "collect").sort((a, b) => priorityRank[b.priority] - priorityRank[a.priority]); const satisfied = tasks.filter((task) => task.status === "satisfied");
  if (!ready) return <p className="loading">Preparing collection and review tasks…</p>;
  function Card({ task }: { task: CollectionTask }) { return <article className={`panel task-card ${task.priority}`}><div className="task-heading"><div><span className={`badge ${task.priority === "high" ? "invalid" : task.priority === "medium" ? "sample" : "entered"}`}>{task.priority}</span><span className="section-label">{task.category === "review" ? "REVIEW EXISTING EVIDENCE" : "COLLECT MISSING EVIDENCE"}</span><h3>{task.title}</h3><p>{task.explanation}</p></div>{task.region && <span className="task-region"><MapPin size={15} />{task.region}</span>}</div><div className="task-metrics"><div><span>Configured target</span><strong>{task.target}</strong></div><div><span>Usable</span><strong>{task.usable}</strong></div><div><span>Potentially recoverable</span><strong>{task.blockedPotential}</strong></div><div><span>Remaining after review</span><strong>{task.remainingAfterPotential}</strong></div></div><div className="button-row"><Link className="button primary" href={task.actionHref} onClick={() => { if (task.status === "open") void setCollectionTaskStatus(task, "in-progress"); }}>{task.category === "review" ? <ClipboardCheck size={17} /> : <Play size={17} />}{task.actionLabel}</Link>{task.status === "open" && <button className="text-button" onClick={() => void setCollectionTaskStatus(task, "in-progress")}>Mark in progress</button>}{task.status !== "dismissed" && <button className="text-button" onClick={() => void setCollectionTaskStatus(task, "dismissed")}><X size={16} />Dismiss</button>}</div></article>; }
  return <><div className="page-heading with-action"><div><span className="eyebrow">CONFIGURED COLLECTION PLAN</span><h1>Collection &amp; review tasks.</h1><p>Review recoverable evidence before collecting new observations. Remaining quantities are configured collection requirements, not statistical sample-size claims.</p></div><div className="field readiness-country"><label>Country</label><select value={country} onChange={(event) => setCountry(event.target.value as "FJ" | "AU")}><option value="FJ">Fiji</option><option value="AU">Australia</option></select></div></div>
    <section className="panel task-hero"><div><span className="section-label">{COUNTRIES[country].toUpperCase()}</span><strong>{review.length}</strong><h2>review task{review.length === 1 ? "" : "s"} first</h2><p>{collect.length} collection task{collect.length === 1 ? "" : "s"} remain after using current evidence.</p></div><div><h3>How tasks are ordered</h3><p>Existing evidence repair, then missing high-priority requirements, geography gaps, remaining configured deficits, and lower-priority improvements.</p><button className="text-button" onClick={() => download(tasks)}><Download size={16} />Export Collection Plan CSV</button></div></section>
    <section className="task-section"><div className="list-heading"><div><span className="section-label">CATEGORY A</span><h2>Review existing evidence <span className="count-chip">{review.length}</span></h2><p className="small muted">Potentially usable records are prioritized before new collection.</p></div></div>{review.length ? <div className="task-list">{review.map((task) => <Card task={task} key={task.id} />)}</div> : <div className="panel empty-state"><CheckCircle2 size={27} /><h3>No existing evidence needs task-level review.</h3><p>Quality and validation changes will reopen relevant tasks automatically.</p></div>}</section>
    <section className="task-section"><div className="list-heading"><div><span className="section-label">CATEGORY B</span><h2>Collect genuinely missing evidence <span className="count-chip">{collect.length}</span></h2><p className="small muted">Use the existing voice, text, and manual observation workflow.</p></div></div>{collect.length ? <div className="task-list">{collect.map((task) => <Card task={task} key={task.id} />)}</div> : <div className="panel empty-state"><CheckCircle2 size={27} /><h3>Configured requirements are satisfied.</h3><p>New quality blockers or invalidated evidence will produce tasks again.</p></div>}</section>
    {satisfied.length > 0 && <section className="panel task-satisfied"><CheckCircle2 size={19} /><span>{satisfied.length} configured collection task{satisfied.length === 1 ? "" : "s"} currently satisfied.</span><button className="text-button" onClick={() => setShowDismissed(!showDismissed)}>{showDismissed ? "Hide dismissed" : "Show dismissed"}</button></section>}
  </>;
}
