"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Check, ChevronRight, Download, Info, SlidersHorizontal } from "lucide-react";
import { compileDraft, compilationPackage, DEFAULT_DRAFT_COMPILATION, approveCommodity, type PreliminaryCommodityEstimate } from "@/lib/compilation";
import { COMMODITIES, COUNTRIES, type DraftCompilationState, type ReadinessCommodity } from "@/lib/types";
import { useWorkspace } from "./workspace";

const names: Record<ReadinessCommodity, string> = { ...COMMODITIES, coconut: "Coconut", tuna: "Tuna" };
function percent(value: number | null) { return value === null ? "—" : `${value.toFixed(1)}%`; }
function download(name: string, body: string, type: string) { const url = URL.createObjectURL(new Blob([body], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export function CompilationScreen() {
  const { state, ready, saveDraftCompilation, approveCompilationCommodity } = useWorkspace(); const [selected, setSelected] = useState<ReadinessCommodity | null>(null); const [configOpen, setConfigOpen] = useState(false);
  const draft = state.draftCompilation ?? DEFAULT_DRAFT_COMPILATION; const summary = useMemo(() => compileDraft({ ...state, draftCompilation: draft }), [state, draft]); const selectedRow = summary.rows.find((row) => row.commodity === selected) ?? null;
  if (!ready) return <p className="loading">Opening draft compilation workspace…</p>;
  function saveConfig(patch: Partial<DraftCompilationState["config"]>) { void saveDraftCompilation({ ...draft, config: { ...draft.config, ...patch } }); }
  function toggleCommodity(commodity: ReadinessCommodity) { const exists = draft.config.commodityBasket.some((item) => item.commodity === commodity); const basket = exists ? draft.config.commodityBasket.filter((item) => item.commodity !== commodity) : [...draft.config.commodityBasket, { id: crypto.randomUUID(), commodity, foodGroup: null, productionWeight: null }]; saveConfig({ commodityBasket: basket }); }
  function approve(row: PreliminaryCommodityEstimate) { const approval = approveCommodity({ ...state, draftCompilation: draft }, row); if (approval) void approveCompilationCommodity(approval); }
  function exportJson() { download("draft-national-compilation.json", JSON.stringify(compilationPackage(summary, state), null, 2), "application/json"); }
  function exportCsv() { const header = ["commodity", "current_estimate_percent", "baseline_estimate_percent", "approved", "usable_observations", "blocked", "sources", "regions", "measurement_methods", "warnings"]; const rows = summary.rows.map((row) => [row.commodity, row.currentEstimate ?? "", row.baselineEstimate ?? "", row.approved ? "yes" : "no", row.usableCount, row.blockedCount, row.sourceNames.join("; "), row.regions.join("; "), row.measurementMethods.join("; "), row.openWarningIds.join("; ")]); const quote = (value: unknown) => `"${String(value).replaceAll('"', '""')}"`; download("draft-national-compilation.csv", [header, ...rows].map((row) => row.map(quote).join(",")).join("\n"), "text/csv;charset=utf-8"); }
  return <><div className="page-heading with-action"><div><span className="eyebrow">NATIONAL EVIDENCE WORKSPACE</span><h1>Draft national compilation.</h1><p>Inspect whether current evidence could support preliminary commodity estimates. This workspace does not produce an official index.</p></div><div className="button-row"><button className="button secondary" onClick={() => setConfigOpen(!configOpen)}><SlidersHorizontal size={17} />{configOpen ? "Close configuration" : "Configure compilation"}</button><div className="field"><label>Country</label><select value={draft.config.country} onChange={(event) => saveConfig({ country: event.target.value as "FJ" | "AU" })}><option value="FJ">Fiji</option><option value="AU">Australia</option></select></div></div></div>
    <section className="panel compilation-warning"><AlertTriangle size={19} /><p><strong>Not an official FAO/SDG submission.</strong> Results require appropriate national statistical methodology and review. Observation Loss Estimates and preliminary commodity estimates must not be treated as nationally representative by default.</p></section>
    <section className="panel compilation-status"><div><span className="section-label">PROTOTYPE FLI DATA READINESS</span><strong>{summary.readinessPercent}%</strong><Link href="/readiness">View readiness matrix<ChevronRight size={15} /></Link></div><div><span className="section-label">DRAFT COMPILATION STATUS</span><strong className={summary.draftAvailable ? "available" : "incomplete"}>{summary.draftAvailable ? "AVAILABLE" : "INCOMPLETE"}</strong><span className="small muted">{summary.availableInputs}/{summary.totalInputs} configured inputs available</span></div>{summary.draftAvailable && <div><span className="section-label">DRAFT NATIONAL COMPILATION</span><strong>{percent(summary.currentNationalEstimate)}</strong><span className="small muted">Prototype calculation · approved inputs</span></div>}</section>
    {!summary.draftAvailable && <section className="panel compilation-blockers"><div className="list-heading"><div><span className="section-label">DRAFT COMPILATION UNAVAILABLE</span><h2>Blocking requirements</h2></div><Link className="text-button" href="/gaps">View blocking evidence gaps<ChevronRight size={16} /></Link></div><ul>{summary.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></section>}
    {summary.draftAvailable && <section className="panel compilation-available"><Check size={19} /><div><strong>Draft national compilation inputs are complete.</strong><p>The displayed number is a prototype calculation from approved observation-derived estimates.</p></div></section>}
    <section className="panel compilation-table"><div className="list-heading"><div><span className="section-label">PRELIMINARY COMMODITY ESTIMATES</span><h2>Configured commodity basket</h2></div><div className="button-row"><button className="text-button" onClick={exportJson}><Download size={15} />Export JSON package</button><button className="text-button" onClick={exportCsv}><Download size={15} />Export CSV</button></div></div><div className="table-scroll"><table className="compilation-grid"><thead><tr><th>Commodity</th><th>Current estimate</th><th>Baseline</th><th>Evidence</th><th>Readiness</th><th>Approval</th></tr></thead><tbody>{summary.rows.map((row) => <tr key={row.commodity} onClick={() => setSelected(row.commodity)}><th>{names[row.commodity]}{row.foodGroup && <small>{row.foodGroup}</small>}</th><td>{percent(row.currentEstimate)}</td><td>{percent(row.baselineEstimate)}</td><td>{row.sourceNames.length ? `${row.sourceNames.length} source${row.sourceNames.length === 1 ? "" : "s"} · ${row.usableCount} usable` : "none"}<small>{row.blockedCount ? `${row.blockedCount} blocked` : ""}</small></td><td><span className={`badge ${row.readiness === "Draft-ready" ? "entered" : row.readiness === "Blocked" ? "invalid" : "sample"}`}>{row.readiness}</span></td><td>{row.approved ? <span className="badge entered">Approved</span> : row.currentEstimate !== null ? <button className="button secondary compact" onClick={(event) => { event.stopPropagation(); approve(row); }}>Approve for draft</button> : <span className="small muted">Estimate required</span>}</td></tr>)}</tbody></table></div></section>
    <section className="panel compilation-method"><Info size={18} /><div><strong>Calculation assumptions</strong><p>{summary.calculationExplanation}</p><button className="text-button" onClick={() => setSelected(selected ?? summary.rows[0]?.commodity ?? null)}>Show calculation</button></div></section>
    {selectedRow && <section className="panel compilation-detail"><div className="list-heading"><div><span className="section-label">TRANSPARENT EVIDENCE DETAIL</span><h2>{names[selectedRow.commodity]} preliminary estimate</h2></div><button className="text-button" onClick={() => setSelected(null)}>Close</button></div><p>{selectedRow.explanation}</p><div className="compilation-detail-grid"><div><span>Current estimate</span><strong>{percent(selectedRow.currentEstimate)}</strong></div><div><span>Baseline</span><strong>{percent(selectedRow.baselineEstimate)}</strong></div><div><span>Usable observations</span><strong>{selectedRow.usableCount}</strong></div><div><span>Blocked</span><strong>{selectedRow.blockedCount}</strong></div><div><span>Regions</span><strong>{selectedRow.regions.length || "—"}</strong></div><div><span>Open warnings</span><strong>{selectedRow.openWarningIds.length}</strong></div></div><div className="compilation-detail-columns"><div><h3>Sources</h3>{selectedRow.sourceNames.length ? <ul>{selectedRow.sourceNames.map((source) => <li key={source}>{source}</li>)}</ul> : <p className="muted">No source evidence.</p>}</div><div><h3>Measurement methods</h3>{selectedRow.measurementMethods.length ? <ul>{selectedRow.measurementMethods.map((method) => <li key={method}>{method}</li>)}</ul> : <p className="muted">No usable methods.</p>}</div></div><p className="small muted">Source IDs: {selectedRow.sourceIds.join(", ") || "none"}. Record IDs: {selectedRow.currentEvidence.map((record) => record.id).join(", ") || "none"}.</p></section>}
    {configOpen && <section className="panel compilation-config"><div className="list-heading"><div><span className="section-label">LOCAL CONFIGURATION</span><h2>Compilation inputs</h2><p className="small muted">This configuration is a local planning model. It is not an official commodity basket or weighting method.</p></div></div><div className="metadata-grid"><label className="field">Baseline year<input type="number" value={draft.config.baselineYear ?? ""} onChange={(event) => saveConfig({ baselineYear: event.target.value ? Number(event.target.value) : null })} /></label><label className="field">Current/reference year<input type="number" value={draft.config.currentYear ?? ""} onChange={(event) => saveConfig({ currentYear: event.target.value ? Number(event.target.value) : null })} /></label><label className="field">Aggregation model<select value={draft.config.aggregationMethod} onChange={(event) => saveConfig({ aggregationMethod: event.target.value as DraftCompilationState["config"]["aggregationMethod"] })}><option value="weighted-production">Production-weighted (weights required)</option><option value="unweighted-demonstration">Unweighted demonstration</option></select></label></div><div className="basket-options"><span className="section-label">COMMODITY BASKET</span>{(["tomatoes", "bananas", "taro", "coconut", "tuna"] as ReadinessCommodity[]).map((commodity) => <label key={commodity}><input type="checkbox" checked={draft.config.commodityBasket.some((item) => item.commodity === commodity)} onChange={() => toggleCommodity(commodity)} />{names[commodity]}</label>)}</div><div className="compilation-weight-list">{draft.config.commodityBasket.map((item) => <label className="field" key={item.id}>{names[item.commodity]} production weight / value<input type="number" min="0" value={item.productionWeight ?? ""} placeholder="Explicitly supplied only" onChange={(event) => saveConfig({ commodityBasket: draft.config.commodityBasket.map((row) => row.id === item.id ? { ...row, productionWeight: event.target.value ? Number(event.target.value) : null } : row) })} /></label>)}</div></section>}
  </>;
}
