"use client";

import { useEffect, useState } from "react";
import { Check, ClipboardCheck, Image as ImageIcon, ShieldAlert } from "lucide-react";
import { COMMODITIES, type DataQualityCategory } from "@/lib/types";
import { detectDataQualityIssues, getRecordQualityStatus, qualityRecords } from "@/lib/quality";
import { getPhotoBlob } from "@/lib/photo-storage";
import { useWorkspace } from "./workspace";

function SourceImage({ imageId }: { imageId: string }) { const [url, setUrl] = useState<string | null>(null); useEffect(() => { let active = true; let objectUrl: string | null = null; void getPhotoBlob(imageId).then((blob) => { if (blob && active) { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } }); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [imageId]); return url ? <img className="quality-image" src={url} alt="Original photo source" /> : <span className="small muted"><ImageIcon size={15} />Original image retained locally</span>; }
const label = (value: string) => value.replaceAll("-", " ");

export function DataQualityScreen() {
  const { state, ready, setQualityIssueStatus, excludeDuplicateRecord } = useWorkspace();
  const [severity, setSeverity] = useState("all"); const [category, setCategory] = useState("all"); const [source, setSource] = useState("all"); const [sourceType, setSourceType] = useState("all"); const [commodity, setCommodity] = useState("all");
  if (!ready) return <p className="loading">Opening quality checks…</p>;
  const issues = detectDataQualityIssues(state); const records = qualityRecords(state); const open = issues.filter((issue) => issue.status === "open");
  const filtered = issues.filter((issue) => (severity === "all" || issue.severity === severity) && (category === "all" || issue.category === category) && (source === "all" || issue.sourceIds.includes(source)) && (sourceType === "all" || issue.sourceIds.some((id) => state.sources.find((item) => item.id === id)?.sourceType === sourceType)) && (commodity === "all" || issue.recordIds.some((id) => records.find((record) => record.id === id)?.commodity === commodity)));
  const count = (key: DataQualityCategory) => open.filter((issue) => issue.category === key).length;
  return <><div className="page-heading"><span className="eyebrow">CROSS-DATASET CHECKS</span><h1>Data quality.</h1><p>{records.length} normalized records · {open.length} unresolved issues. Review evidence before readiness analysis; no record is removed automatically.</p></div>
    <section className="quality-summary"><div><strong>{count("duplicate")}</strong><span>duplicates</span></div><div><strong>{count("conflict") + count("definition")}</strong><span>definition / value conflicts</span></div><div><strong>{count("geography") + count("time")}</strong><span>geography / time warnings</span></div><div><strong>{count("source-confidence") + count("conversion")}</strong><span>source / conversion blocks</span></div></section>
    <section className="panel filters quality-filters"><ShieldAlert size={18} /><div className="field"><label>Severity</label><select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">All</option><option value="error">Error</option><option value="warning">Warning</option><option value="info">Info</option></select></div><div className="field"><label>Category</label><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All</option>{["duplicate", "conflict", "unit", "definition", "geography", "time", "measurement-method", "source-confidence", "conversion"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div><div className="field"><label>Source</label><select value={source} onChange={(event) => setSource(event.target.value)}><option value="all">All sources</option>{state.sources.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Source type</label><select value={sourceType} onChange={(event) => setSourceType(event.target.value)}><option value="all">All types</option>{[...new Set(state.sources.map((item) => item.sourceType))].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div><div className="field"><label>Commodity</label><select value={commodity} onChange={(event) => setCommodity(event.target.value)}><option value="all">All commodities</option>{Object.entries(COMMODITIES).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></div></section>
    <section className="quality-list">{filtered.length ? filtered.map((issue) => { const compared = issue.recordIds.map((id) => records.find((record) => record.id === id)).filter(Boolean); const excluded = issue.recordIds.some((id) => state.duplicateExcludedRecordIds.includes(id)); const duplicateTarget = issue.category === "duplicate" ? issue.recordIds.slice().reverse().find((id) => state.records.some((record) => record.id === id)) : undefined; return <article className={`panel quality-issue ${issue.severity}`} key={issue.id}><div className="quality-heading"><div><span className="badge invalid">{issue.severity}</span><span className="section-label">{label(issue.category)}</span><h2>{issue.title}</h2><p>{issue.explanation}</p></div><span className="small muted">{issue.status === "open" ? "Needs review" : issue.status}</span></div>{compared.length > 0 && <div className="quality-compare">{compared.slice(0, 2).map((record) => record && <div key={record.id}><span className="section-label">{record.source?.name || "Unlinked source"}</span><strong>{record.commodity || "Commodity unresolved"}</strong><p>{record.location || "Location unresolved"} · {record.stage || "Stage unresolved"} · {record.date || "Date unresolved"}</p><p><b>{record.affectedKg ?? "—"} kg affected</b> · {record.measurement || "method unknown"}</p><p className="small muted">{record.source?.originalFilename || "Field observation"}{record.confirmed ? " · confirmed" : " · mapped candidate"} · quality: {getRecordQualityStatus(record.id, issues, state.duplicateExcludedRecordIds)}</p>{record.imageId && <SourceImage imageId={record.imageId} />}</div>)}</div>}{issue.status === "open" && <div className="button-row quality-actions">{issue.category === "duplicate" && duplicateTarget && !excluded && <button className="button primary" onClick={() => void excludeDuplicateRecord(duplicateTarget, issue)}><Check size={17} />Mark duplicate</button>}<button className="button secondary" onClick={() => void setQualityIssueStatus(issue, "accepted")}>Keep both</button><button className="text-button" onClick={() => void setQualityIssueStatus(issue, "resolved")}><ClipboardCheck size={17} />Mark reviewed</button></div>}{excluded && <p className="small muted">A duplicate was excluded from aggregate/readiness counting; source evidence remains preserved.</p>}</article>; }) : <section className="panel empty-state"><ClipboardCheck size={28} /><h2>No issues match these filters.</h2><p>Quality decisions are stored locally with the source evidence.</p></section>}</section></>;
}
