"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ChevronRight, FileWarning, MapPin, ShieldAlert } from "lucide-react";
import { COUNTRIES, STAGES, type EvidenceGap } from "@/lib/types";
import { detectEvidenceGaps } from "@/lib/evidence-gaps";
import { useWorkspace } from "./workspace";

const typeLabel: Record<EvidenceGap["type"], string> = { "missing-data": "Evidence coverage", "geographic-coverage": "Geographic coverage", "time-coverage": "Time coverage", "missing-field": "Missing critical field", "quality-blocker": "Data-quality blocker", "source-confidence": "Source review", "measurement-method": "Measurement method", baseline: "Baseline", fragmentation: "Fragmentation" };
const severityOrder = { high: 3, medium: 2, low: 1 };

export function EvidenceGapsScreen() {
  const { state, ready } = useWorkspace(); const [country, setCountry] = useState<"FJ" | "AU">("FJ"); const [severity, setSeverity] = useState<"all" | EvidenceGap["severity"]>("all"); const [type, setType] = useState<"all" | EvidenceGap["type"]>("all");
  const summary = useMemo(() => detectEvidenceGaps(state, country), [state, country]); const visible = summary.gaps.filter((gap) => (severity === "all" || gap.severity === severity) && (type === "all" || gap.type === type)).sort((a, b) => severityOrder[b.severity] - severityOrder[a.severity]);
  if (!ready) return <p className="loading">Checking evidence gaps…</p>;
  const why = [summary.missingRequirementCount ? `${summary.missingRequirementCount} commodity-stage requirement${summary.missingRequirementCount === 1 ? " contains" : "s contain"} no usable evidence` : null, summary.missingRegionCount ? `${summary.missingRegionCount} configured region${summary.missingRegionCount === 1 ? " has" : "s have"} no coverage` : null, summary.blockedRecordCount ? `${summary.blockedRecordCount} observation${summary.blockedRecordCount === 1 ? " is" : "s are"} blocked` : null, summary.baselineGapCount ? `${summary.baselineGapCount} baseline requirement${summary.baselineGapCount === 1 ? " is" : "s are"} missing` : null].filter(Boolean);
  return <><div className="page-heading with-action"><div><span className="eyebrow">CONFIGURED COLLECTION REQUIREMENTS</span><h1>Evidence gaps.</h1><p>Deterministic explanations of evidence still missing or blocked before configured readiness requirements can be satisfied.</p></div><div className="field readiness-country"><label>Country</label><select value={country} onChange={(event) => setCountry(event.target.value as "FJ" | "AU")}><option value="FJ">Fiji</option><option value="AU">Australia</option></select></div></div>
    <section className="panel gap-hero"><div><span className="section-label">WHY AREN&apos;T WE READY?</span><strong>{summary.majorGapCount}</strong><h2>major evidence gap{summary.majorGapCount === 1 ? "" : "s"}</h2><p>{summary.gaps.length ? `${summary.gaps.length} unresolved deterministic gap${summary.gaps.length === 1 ? "" : "s"} affect configured readiness requirements for ${COUNTRIES[country]}.` : `No unresolved configured evidence gaps for ${COUNTRIES[country]}.`}</p></div><ul>{why.length ? why.map((item) => <li key={item}>{item}</li>) : <li>Configured evidence is currently complete.</li>}</ul></section>
    {summary.recoverableRecordCount > 0 && <section className="panel gap-recoverable"><FileWarning size={20} /><div><strong>Existing evidence that may be recoverable</strong><p>{summary.recoverableRecordCount} record{summary.recoverableRecordCount === 1 ? " needs" : "s need"} review, completion, or source-confidence resolution before they can contribute more fully.</p></div><Link href="/quality" className="text-button">Open quality checks<ChevronRight size={16} /></Link></section>}
    <section className="panel filters gap-filters"><AlertTriangle size={18} /><div className="field"><label>Severity</label><select value={severity} onChange={(event) => setSeverity(event.target.value as typeof severity)}><option value="all">All severities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><div className="field"><label>Gap type</label><select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="all">All gap types</option>{Object.entries(typeLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div></section>
    <section className="gap-list">{visible.length ? visible.map((gap) => { const sources = gap.sourceIds.map((id) => state.sources.find((source) => source.id === id)?.name).filter(Boolean); return <article className={`panel gap-card ${gap.severity}`} key={gap.id}><div className="gap-heading"><div><span className={`badge ${gap.severity === "high" ? "invalid" : gap.severity === "medium" ? "sample" : "entered"}`}>{gap.severity}</span><span className="section-label">{typeLabel[gap.type]}</span><h2>{gap.title}</h2><p>{gap.explanation}</p></div>{gap.region && <span className="gap-region"><MapPin size={15} />{gap.region}</span>}</div><dl className="gap-details"><div><dt>Requirement</dt><dd>{gap.commodity ? `${gap.commodity} · ${gap.stage ? STAGES[gap.stage] : "all stages"}` : "Source review"}</dd></div><div><dt>Supporting records</dt><dd>{gap.supportingRecordIds.length}</dd></div><div><dt>Quality issues</dt><dd>{gap.blockingIssueIds.length}</dd></div><div><dt>Sources</dt><dd>{sources.length ? sources.join(", ") : "No matching source evidence"}</dd></div></dl><div className="button-row"><Link className="button secondary" href="/records">View supporting records<ChevronRight size={16} /></Link><Link className="button secondary" href="/datasets">View source evidence<ChevronRight size={16} /></Link>{gap.blockingIssueIds.length > 0 && <Link className="button secondary" href="/quality"><ShieldAlert size={16} />View quality issues</Link>}</div></article>; }) : <section className="panel empty-state"><AlertTriangle size={28} /><h2>No evidence gaps match these filters.</h2><p>Changes to evidence, validation decisions, or configured requirements recalculate this list automatically.</p></section>}</section>
  </>;
}
