"use client";
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Camera, Check, ImagePlus, LoaderCircle, Trash2 } from "lucide-react";
import { confirmDraft } from "@/lib/domain";
import { documentObservationToDraft, type ExtractedDocumentObservation } from "@/lib/document-extraction";
import { getPhotoBlob, savePhotoBlob } from "@/lib/photo-storage";
import { photoProvenance } from "@/lib/provenance";
import { DATASET_SOURCE_TYPES, type DatasetSourceType, type PhotoCandidate, type PhotoSource } from "@/lib/types";
import { useWorkspace } from "./workspace";
import { ReviewFields } from "./review-fields";

export function PhotoScanScreen() {
  const { state, ready, savePhotoSource, saveRecord, updatePhotoSource } = useWorkspace(); const picker = useRef<HTMLInputElement>(null); const search = useSearchParams();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [sourceName, setSourceName] = useState(""); const [organisation, setOrganisation] = useState(""); const [country, setCountry] = useState(""); const [year, setYear] = useState(""); const [location, setLocation] = useState(""); const [sourceType, setSourceType] = useState<DatasetSourceType>("other"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [source, setSource] = useState<PhotoSource | null>(null); const [queue, setQueue] = useState<PhotoCandidate[]>([]); const [active, setActive] = useState(0);
  useEffect(() => { const requested = search.get("source"); if (!ready || !requested || source) return; const existing = state.photoSources.find((item) => item.id === requested); if (!existing) return; setSource(existing); setQueue(existing.pendingCandidates ?? []); void getPhotoBlob(existing.imageId).then((blob) => { if (blob) setPreview(URL.createObjectURL(blob)); }); }, [ready, search, source, state.photoSources]);
  function choose(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0]; event.target.value = ""; if (!next) return; if (!["image/jpeg", "image/png", "image/webp"].includes(next.type)) { setError("Choose a JPG, PNG or WebP image."); return; } if (next.size > 8 * 1024 * 1024) { setError("Keep the image under 8 MB."); return; } setFile(next); setPreview(URL.createObjectURL(next)); setError(null); }
  async function extract(manual = false) { if (!file) return; setBusy(true); setError(null); const imageId = crypto.randomUUID(); const photo: PhotoSource = { id: crypto.randomUUID(), imageId, originalFilename: file.name, mimeType: file.type, sourceName: sourceName.trim() || null, organisation: organisation.trim() || null, country: country.trim() || null, reportingYear: /^\d{4}$/.test(year) ? Number(year) : null, location: location.trim() || null, sourceType, importedAt: new Date().toISOString(), extractedAt: manual ? null : new Date().toISOString(), extractionMethod: manual ? "manual-from-photo" : "openai-vision", detectedCount: manual ? 1 : 0, confirmedRecordIds: [], documentWarnings: [], pendingCandidates: [] };
    try { if (manual) { const draft = documentObservationToDraft({ commodity: null, country: null, region: null, location: null, date: null, stage: null, incoming: null, affected: null, allocations: [], cause: null, measurement: null, notes: "Manual observation created from photo/scan.", confidenceByField: {}, unresolvedFields: [] }, { country: country.trim().toLowerCase() === "australia" ? "AU" : country.trim().toLowerCase() === "fiji" ? "FJ" : null, location: location.trim() || null }); const pendingCandidates: PhotoCandidate[] = [{ draft, original: draft, index: 0, confidence: {}, unresolved: [] }]; const saved = { ...photo, pendingCandidates }; await savePhotoBlob(imageId, file); await savePhotoSource(saved); setSource(saved); setQueue(pendingCandidates); return; }
      const form = new FormData(); form.append("image", file, file.name); form.append("sourceName", sourceName); form.append("organisation", organisation); form.append("country", country); form.append("year", year); form.append("location", location); const response = await fetch("/api/extract-document", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Document extraction failed."); if (!data.observations.length) throw new Error("No observations were detected. Create an observation manually from this source."); const defaults = { country: country.trim().toLowerCase() === "australia" ? "AU" as const : country.trim().toLowerCase() === "fiji" ? "FJ" as const : null, location: location.trim() || null }; const nextQueue = (data.observations as ExtractedDocumentObservation[]).map((observation, index) => { const draft = documentObservationToDraft(observation, defaults); return { draft, original: draft, index, confidence: observation.confidenceByField, unresolved: observation.unresolvedFields }; }); const savedSource = { ...photo, detectedCount: nextQueue.length, documentWarnings: data.documentWarnings, pendingCandidates: nextQueue }; await savePhotoBlob(imageId, file); await savePhotoSource(savedSource); setSource(savedSource); setQueue(nextQueue);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "The image could not be processed."); } finally { setBusy(false); }
  }
  async function confirm() { const current = queue[active]; if (!source || !current) return; const record = confirmDraft(current.draft, undefined, photoProvenance(source, current.original, current.draft, current.index, current.confidence)); await saveRecord(record); const remaining = queue.filter((_, index) => index !== active); const updated = { ...source, confirmedRecordIds: [...source.confirmedRecordIds, record.id], pendingCandidates: remaining }; await updatePhotoSource(updated); setSource(updated); setQueue(remaining); setActive(0); }
  if (queue.length && source) { const current = queue[active]; return <><div className="page-heading"><span className="eyebrow">PHOTO / SCAN REVIEW</span><h1>{queue.length} observation{queue.length === 1 ? "" : "s"} need review.</h1><p>Original image remains local. Nothing is saved as an observation until you confirm it.</p></div>{preview && <img className="photo-thumb" src={preview} alt="Uploaded source" />}<div className="notice warning">{current.unresolved.length ? `Review unresolved fields: ${current.unresolved.join(", ")}.` : "Check every extracted value against the source."}{Object.entries(current.confidence).filter(([, value]) => value < .7).length > 0 && " Some extracted fields have low confidence."}</div><section className="panel review-panel"><ReviewFields draft={current.draft} onChange={(draft) => { const next = queue.map((item, index) => index === active ? { ...item, draft } : item); setQueue(next); void updatePhotoSource({ ...source, pendingCandidates: next }); }} onConfirm={() => void confirm()} /></section><div className="button-row"><button className="text-button" onClick={() => { const next = queue.filter((_, index) => index !== active); setQueue(next); void updatePhotoSource({ ...source, pendingCandidates: next }); }}><Trash2 size={17} />Discard candidate</button></div></>; }
  if (source) return <><div className="page-heading"><span className="eyebrow">PHOTO / SCAN SAVED</span><h1>Source evidence retained locally.</h1><p>Confirmed observations are now in Records; the original image remains linked as provenance.</p></div><section className="panel photo-summary">{preview && <img className="photo-preview" src={preview} alt={`Original source ${source.originalFilename}`} />}<div><span className="section-label">SOURCE</span><h2>{source.sourceName || source.originalFilename}</h2><p>{source.originalFilename}</p><dl><div><dt>Extracted</dt><dd>{source.detectedCount} observation{source.detectedCount === 1 ? "" : "s"}</dd></div><div><dt>Validated</dt><dd>{source.confirmedRecordIds.length}</dd></div><div><dt>Needs review</dt><dd>{Math.max(0, source.detectedCount - source.confirmedRecordIds.length)}</dd></div></dl>{source.documentWarnings.length > 0 && <div className="notice warning">{source.documentWarnings.join(" ")}</div>}<div className="button-row"><Link className="button secondary" href="/records">View records</Link><Link className="button primary" href="/datasets/photo">Import another photo</Link></div></div></section></>;
  return <><div className="page-heading"><span className="eyebrow">PHOTO / SCAN</span><h1>Extract evidence from a paper record.</h1><p>Upload a notebook page, survey sheet, tally, or scanned form. The image stays in this browser.</p></div><section className="panel photo-import"><input ref={picker} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={choose} /><button className="drop-zone" type="button" onClick={() => picker.current?.click()}><ImagePlus size={34} /><h2>{file ? file.name : "Choose a photo or scan"}</h2><p>JPG, PNG or WebP · up to 8 MB</p></button>{preview && <img className="photo-preview" src={preview} alt="Selected source preview" />}<div className="metadata-grid"><div className="field"><label>Source name</label><input value={sourceName} onChange={(event) => setSourceName(event.target.value)} placeholder="Photographed field notebook" /></div><div className="field"><label>Organisation</label><input value={organisation} onChange={(event) => setOrganisation(event.target.value)} /></div><div className="field"><label>Country</label><input value={country} onChange={(event) => setCountry(event.target.value)} /></div><div className="field"><label>Year</label><input value={year} onChange={(event) => setYear(event.target.value)} /></div><div className="field"><label>Location if known</label><input value={location} onChange={(event) => setLocation(event.target.value)} /></div><div className="field"><label>Source type</label><select value={sourceType} onChange={(event) => setSourceType(event.target.value as DatasetSourceType)}>{Object.entries(DATASET_SOURCE_TYPES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div>{error && <div className="notice error">{error}</div>}{busy && <div className="processing"><LoaderCircle className="spinner" size={18} />Extracting supported observations…</div>}<div className="import-actions"><Link className="text-button" href="/datasets"><ArrowLeft size={17} />Back to datasets</Link><div className="button-row"><button className="button secondary" disabled={!file || busy} onClick={() => void extract(true)}><Camera size={18} />Create manually from source</button><button className="button primary" disabled={!file || busy} onClick={() => void extract()}><Check size={18} />Extract observations</button></div></div></section></>;
}
