"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Check, ChevronRight, CircleAlert, Settings2 } from "lucide-react";
import { COMMODITIES, COUNTRIES, STAGES, type ReadinessCommodity, type ReadinessRequirement, type Stage } from "@/lib/types";
import { evaluateReadiness, type ReadinessCell } from "@/lib/readiness";
import { useWorkspace } from "./workspace";

const commodityNames: Record<ReadinessCommodity, string> = { ...COMMODITIES, coconut: "Coconut", tuna: "Tuna" };
const cellMark = (status: ReadinessCell["status"]) => status === "satisfied" ? "✓" : status === "partial" ? "⚠" : status === "blocked" ? "⛔" : status === "missing" ? "●" : "—";

export function ReadinessScreen() {
  const { state, ready, saveReadinessRequirements } = useWorkspace(); const [country, setCountry] = useState<"FJ" | "AU">("FJ"); const [selectedId, setSelectedId] = useState<string | null>(null); const [configOpen, setConfigOpen] = useState(false);
  const summary = useMemo(() => evaluateReadiness(state, country), [state, country]); const commodities = [...new Set(summary.cells.map((cell) => cell.requirement.commodity))]; const stages = Object.keys(STAGES) as Stage[]; const selected = summary.cells.find((cell) => cell.requirement.id === selectedId) ?? null;
  const sourceBreakdown = useMemo(() => { const sourceIds = new Set(summary.cells.flatMap((cell) => cell.sourceIds)); const labels = { csv: "CSV datasets", xlsx: "Excel datasets", image: "Paper / photo sources", voice: "Voice observations", "manual-text": "Manual observations" } as const; return (Object.keys(labels) as (keyof typeof labels)[]).map((format) => ({ label: labels[format], count: state.sources.filter((source) => sourceIds.has(source.id) && source.inputFormat === format).length })).filter((item) => item.count); }, [state.sources, summary.cells]);
  function update(id: string, patch: Partial<ReadinessRequirement>) { void saveReadinessRequirements(state.readinessRequirements.map((item) => item.id === id ? { ...item, ...patch } : item)); }
  function addRequirement() { const requirement: ReadinessRequirement = { id: crypto.randomUUID(), country, commodity: "tomatoes", stage: "handling", requiredRegions: [], targetObservations: 1, acceptedMeasurementMethods: ["weighed", "estimated", "unknown"], baselineRequired: false, priorityWeight: 1 }; void saveReadinessRequirements([...state.readinessRequirements, requirement]); }
  if (!ready) return <p className="loading">Opening readiness matrix…</p>;
  return <><div className="page-heading with-action"><div><span className="eyebrow">NATIONAL EVIDENCE OVERVIEW</span><h1>Prototype FLI Data Readiness.</h1><p>This is an internal evidence-completeness indicator based on configured collection requirements. It is not an official FAO statistic or determination of national representativeness.</p></div><div className="field readiness-country"><label>Country</label><select value={country} onChange={(event) => { setCountry(event.target.value as "FJ" | "AU"); setSelectedId(null); }}><option value="FJ">Fiji</option><option value="AU">Australia</option></select></div></div>
    <section className="panel readiness-hero"><div><span className="section-label">{COUNTRIES[country].toUpperCase()}</span><strong>{summary.score}%</strong><h2>Prototype FLI Data Readiness</h2><p>Configured requirements only; targets are not statistical sample-size or representativeness claims.</p></div><div className="readiness-counts"><span><b>{summary.counts.satisfied}</b>Satisfied</span><span><b>{summary.counts.partial}</b>Partial</span><span><b>{summary.counts.missing}</b>Missing</span><span><b>{summary.counts.blocked}</b>Blocked</span></div></section>
    {sourceBreakdown.length > 0 && <section className="panel readiness-sources"><span className="section-label">SOURCE DISTRIBUTION</span><div>{sourceBreakdown.map((item) => <span key={item.label}><b>{item.count}</b>{item.label}</span>)}</div><p className="small muted">Shown for evidence transparency only; source counts do not increase readiness.</p></section>}
    <section className="panel readiness-disclaimer"><CircleAlert size={20} /><p>Formula: each configured cell receives Missing/Blocked = 0, Partial = 0.5, or Requirement satisfied = 1; the country indicator is the priority-weighted average. Source counts never increase readiness.</p></section>
    <section className="panel readiness-matrix"><div className="list-heading"><div><span className="section-label">CONFIGURED COLLECTION REQUIREMENTS</span><h2>Evidence matrix</h2></div><button className="text-button" onClick={() => setConfigOpen(!configOpen)}><Settings2 size={17} />{configOpen ? "Close configuration" : "Configure requirements"}</button></div>{commodities.length ? <div className="matrix-scroll"><table><thead><tr><th>Commodity</th>{stages.map((stage) => <th key={stage}>{STAGES[stage]}</th>)}</tr></thead><tbody>{commodities.map((commodity) => <tr key={commodity}><th>{commodityNames[commodity]}</th>{stages.map((stage) => { const cell = summary.cells.find((item) => item.requirement.commodity === commodity && item.requirement.stage === stage); return <td key={stage}>{cell ? <button className={`readiness-cell ${cell.status}`} onClick={() => setSelectedId(cell.requirement.id)}><span>{cellMark(cell.status)}</span>{cell.status === "satisfied" ? "Satisfied" : cell.status}</button> : <span className="readiness-na">N/A</span>}</td>; })}</tr>)}</tbody></table></div> : <div className="empty-state"><h3>No configured requirements for {COUNTRIES[country]}</h3><button className="button primary" onClick={addRequirement}>Add collection requirement</button></div>}</section>
    {selected && <section className="panel readiness-detail"><div><span className={`badge ${selected.status === "satisfied" ? "entered" : selected.status === "blocked" ? "invalid" : "sample"}`}>{selected.status}</span><h2>{commodityNames[selected.requirement.commodity]} · {STAGES[selected.requirement.stage]}</h2><p>{selected.explanation}</p></div><div className="readiness-detail-grid"><div><span>Usable observations</span><strong>{selected.usable.length}</strong></div><div><span>Partial / warnings</span><strong>{selected.partial.length}</strong></div><div><span>Blocked</span><strong>{selected.blocked.length}</strong></div><div><span>Configured regions</span><strong>{selected.requirement.requiredRegions.length ? `${selected.representedRegions.length}/${selected.requirement.requiredRegions.length}` : "Not configured"}</strong></div><div><span>Baseline</span><strong>{selected.requirement.baselineRequired ? selected.baselinePresent ? "Available" : "Missing" : "Not required"}</strong></div></div><div className="button-row"><Link className="button secondary" href="/records">View supporting records<ChevronRight size={17} /></Link><Link className="button secondary" href="/datasets">View source evidence<ChevronRight size={17} /></Link><Link className="button secondary" href="/quality">View quality issues<ChevronRight size={17} /></Link></div></section>}
    {configOpen && <section className="panel readiness-config"><div className="list-heading"><div><span className="section-label">LOCAL CONFIGURATION</span><h2>Configured collection requirements</h2><p className="small muted">Edit requirements to reflect your collection plan. They do not establish national representativeness.</p></div><button className="button secondary" onClick={addRequirement}><Check size={17} />Add requirement</button></div>{state.readinessRequirements.filter((item) => item.country === country).map((item) => <div className="readiness-config-row" key={item.id}><select value={item.commodity} onChange={(event) => update(item.id, { commodity: event.target.value as ReadinessCommodity })}>{Object.entries(commodityNames).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select><select value={item.stage} onChange={(event) => update(item.id, { stage: event.target.value as Stage })}>{Object.entries(STAGES).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select><label>Target<input type="number" min="1" value={item.targetObservations} onChange={(event) => update(item.id, { targetObservations: Math.max(1, Number(event.target.value) || 1) })} /></label><label>Regions<input value={item.requiredRegions.join(", ")} onChange={(event) => update(item.id, { requiredRegions: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} placeholder="Comma-separated" /></label><label>Priority<select value={item.priorityWeight} onChange={(event) => update(item.id, { priorityWeight: Number(event.target.value) as 1 | 2 | 3 })}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option></select></label><label className="readiness-checkbox"><input type="checkbox" checked={item.baselineRequired} onChange={(event) => update(item.id, { baselineRequired: event.target.checked })} />Baseline required</label></div>)}</section>}</>;
}
