"use client";

import { useRef, useState } from "react";
import { Check, Plus, Trash2 } from "lucide-react";
import { evaluateDraft, formatMass, normalizeQuantity } from "@/lib/domain";
import { COMMODITIES, COUNTRIES, DESTINATIONS, STAGES, type Draft, type Issue, type Quantity, type Destination } from "@/lib/types";
import { ContextFields } from "./context-fields";

function QuantityField({ label, name, quantity, onChange, issues, evidence }: { label: string; name: string; quantity: Quantity; onChange: (value: Quantity) => void; issues: Issue[]; evidence?: string }) {
  const errors = issues.filter((issue) => issue.field.startsWith(name));
  const number = (value: string) => value === "" || !Number.isFinite(Number(value)) ? null : Number(value);
  return <div className="quantity-field"><div className="quantity-inputs">
    <div className="field"><label htmlFor={`${name}-amount`}>{label}</label><input id={`${name}-amount`} type="number" inputMode="decimal" step="any" value={quantity.amount ?? ""} onChange={(event) => onChange({ ...quantity, amount: number(event.target.value) })} aria-invalid={errors.some((issue) => issue.field.endsWith("amount"))} aria-describedby={errors.length ? `${name}-errors` : undefined} placeholder="Enter quantity" /></div>
    <div className="field unit-field"><label htmlFor={`${name}-unit`}>Unit</label><select id={`${name}-unit`} value={quantity.unit} onChange={(event) => onChange({ ...quantity, unit: event.target.value as Quantity["unit"] })}><option value="unknown">Choose unit</option><option value="kg">kg</option><option value="g">grams</option><option value="tonnes">tonnes</option><option value="crates">crates</option></select></div></div>
    {quantity.unit === "crates" && <div className="field crate-field"><label htmlFor={`${name}-crate-weight`}>Kilograms per crate · {label.toLowerCase()}</label><input id={`${name}-crate-weight`} type="number" step="any" inputMode="decimal" value={quantity.kgPerCrate ?? ""} onChange={(event) => onChange({ ...quantity, kgPerCrate: number(event.target.value) })} placeholder="Officer-provided conversion" /></div>}
    {evidence && <p className="evidence"><span>From observation</span> “{evidence}”</p>}
    {!!errors.length && <div id={`${name}-errors`} className="field-errors">{errors.map((issue) => <p key={issue.field}>{issue.message}</p>)}</div>}
  </div>;
}

export function ReviewFields({ draft, onChange, onConfirm, busy = false }: { draft: Draft; onChange: (draft: Draft) => void; onConfirm: () => void; busy?: boolean }) {
  const [attempted, setAttempted] = useState(false);
  const summary = useRef<HTMLDivElement>(null);
  const result = evaluateDraft(draft);
  const issues = attempted ? result.issues : result.issues.filter((issue) => issue.kind === "conflict");
  function submit() { setAttempted(true); if (result.issues.length) { requestAnimationFrame(() => summary.current?.focus()); return; } onConfirm(); }
  const allocatedKg = draft.allocations.reduce((sum, allocation) => sum + (normalizeQuantity(allocation.quantity) ?? 0), 0);
  const labels = { country: COUNTRIES, commodity: COMMODITIES, stage: STAGES };
  return <div className="review-layout"><aside className="source-panel"><div className="section-label">01 / THE OBSERVATION</div><h3>The officer’s words</h3><blockquote className="transcript">{draft.transcript || "No spoken or typed observation. This record is being entered manually."}</blockquote><p className="muted small">Keep the original account alongside the reviewed record. AI suggestions need your confirmation.</p><div className="source-context"><span>{COUNTRIES[draft.context.country]}</span><span>{COMMODITIES[draft.context.commodity]}</span><span>{STAGES[draft.context.stage]}</span></div><div className="quiet-note">Rejected food may still be used. Its destination determines which kilograms count as loss.</div></aside>
    <div className="review-form"><div className="section-label">02 / CHECK & COMPLETE</div><h2>Review this record</h2><p className="muted">Check the quantities, fill any gaps, then confirm.</p>
      {attempted && !!result.issues.length && <div className="notice error" role="alert" tabIndex={-1} ref={summary}><strong>{result.issues.length} {result.issues.length === 1 ? "item needs" : "items need"} your attention</strong><ul>{result.issues.map((issue) => <li key={issue.field}>{issue.message}</li>)}</ul></div>}
      {result.issues.filter((issue) => issue.kind === "conflict").map((issue) => {
        const field = issue.field.split(".")[1] as "country" | "commodity" | "stage";
        const detected = draft.detectedContext[field]!;
        const names = labels[field] as Record<string, string>;
        return <div className="notice warning" key={field}><strong>Selected {names[draft.context[field]]}; observation says {names[detected]}.</strong><p>Choose the correct context for this event.</p><div className="button-row"><button className="button secondary" onClick={() => onChange({ ...draft, acknowledgedConflicts: [...draft.acknowledgedConflicts, field] })}>Keep {names[draft.context[field]]}</button><button className="button secondary" onClick={() => onChange({ ...draft, context: { ...draft.context, [field]: detected }, acknowledgedConflicts: [...draft.acknowledgedConflicts, field] })}>Use {names[detected]}</button></div></div>;
      })}
      <details className="context-details"><summary>Edit location, date or selected context</summary><ContextFields context={draft.context} onChange={(context) => onChange({ ...draft, context, acknowledgedConflicts: [] })} /></details>
      <div className="quantities-grid"><QuantityField label="Mass entering this stage" name="incoming" quantity={draft.incoming} onChange={(incoming) => onChange({ ...draft, incoming })} issues={issues} evidence={draft.evidence.incoming} /><QuantityField label="Affected or rejected mass" name="affected" quantity={draft.affected} onChange={(affected) => onChange({ ...draft, affected })} issues={issues} evidence={draft.evidence.affected} /></div>
      <section className="destinations-section" aria-labelledby="destination-title"><div className="section-heading"><h3 id="destination-title">What happened to the affected food?</h3><span className="step-tag">Required if affected mass &gt; 0</span></div><p className="muted small">Choose a destination for all of it, or add rows to split the quantity.</p>
        <div className="destination-shortcuts">{(["discarded", "composted", "donated", "resold", "animal_feed", "productive_use"] as Destination[]).map((destination) => <button className={`choice-button ${draft.allocations.length === 1 && draft.allocations[0].destination === destination ? "selected" : ""}`} type="button" key={destination} onClick={() => onChange({ ...draft, allocations: [{ destination, quantity: { ...draft.affected } }] })}>{DESTINATIONS[destination]}</button>)}</div>
        {draft.allocations.map((allocation, index) => <div className="allocation-row" key={index}><div className="field"><label htmlFor={`destination-${index}`}>Destination {index + 1}</label><select id={`destination-${index}`} value={allocation.destination} onChange={(event) => onChange({ ...draft, allocations: draft.allocations.map((item, i) => i === index ? { ...item, destination: event.target.value as Destination } : item) })}>{Object.entries(DESTINATIONS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><QuantityField label={`Destination quantity ${index + 1}`} name={`allocations.${index}.quantity`} quantity={allocation.quantity} onChange={(quantity) => onChange({ ...draft, allocations: draft.allocations.map((item, i) => i === index ? { ...item, quantity } : item) })} issues={issues} /><button className="icon-button remove-allocation" aria-label={`Remove destination ${index + 1}`} onClick={() => onChange({ ...draft, allocations: draft.allocations.filter((_, i) => i !== index) })}><Trash2 size={18} /></button></div>)}
        <div className="allocation-footer"><button className="text-button" onClick={() => onChange({ ...draft, allocations: [...draft.allocations, { destination: "unknown", quantity: { amount: null, unit: "kg", kgPerCrate: null } }] })}><Plus size={16} />Add a destination</button>{!!draft.allocations.length && <span className="small tabular">{formatMass(allocatedKg)} / {result.affectedKg === null ? "—" : formatMass(result.affectedKg)} kg allocated</span>}</div>
        {draft.evidence.allocations && <p className="evidence"><span>From observation</span> “{draft.evidence.allocations}”</p>}{issues.filter((issue) => issue.field === "allocations" || issue.field.endsWith("destination")).map((issue) => <p className="field-errors" key={issue.field}>{issue.message}</p>)}
      </section>
      <div className="two-col"><div className="field"><label htmlFor="cause">Reported cause</label><input id="cause" value={draft.cause ?? ""} onChange={(event) => onChange({ ...draft, cause: event.target.value || null })} placeholder="Cause unknown" maxLength={500} />{draft.evidence.cause && <p className="evidence"><span>From observation</span> “{draft.evidence.cause}”</p>}</div><div className="field"><label htmlFor="measurement">How were quantities obtained?</label><select id="measurement" value={draft.measurement} onChange={(event) => onChange({ ...draft, measurement: event.target.value as Draft["measurement"] })}><option value="unknown">Unknown</option><option value="weighed">Weighed</option><option value="estimated">Estimated</option></select></div></div>
      <div className="calculation-strip"><div><span className="small muted">Observation Loss Estimate</span><strong className="tabular">{result.lossKg === null ? "Awaiting complete information" : `${formatMass(result.lossKg)} kg · ${result.lossPercent!.toFixed(1)}%`}</strong></div><p>Discarded + composted ÷ mass entering stage.<br />An observation-derived batch/stage estimate, not the official Food Loss Index.</p></div><div className="confirm-row"><p className="small muted">By confirming, you’ve checked the details against your observation.</p><button className="button primary" onClick={submit} disabled={busy}><Check size={18} />{busy ? "Saving…" : "Confirm record"}</button></div>
    </div></div>;
}
