import { detectEvidenceGaps } from "./evidence-gaps";
import { evaluateReadiness, type ReadinessCell } from "./readiness";
import type { CollectionTask, CollectionTaskStatus, Context, Country, EvidenceGap, StoredState } from "./types";

const commodityName = { tomatoes: "Tomato", bananas: "Banana", taro: "Taro", coconut: "Coconut", tuna: "Tuna" } as const;
const priority = (weight: 1 | 2 | 3, urgent = false): CollectionTask["priority"] => urgent || weight === 3 ? "high" : weight === 2 ? "medium" : "low";
const taskState = (state: StoredState, id: string, satisfied = false): CollectionTaskStatus => satisfied ? "satisfied" : state.collectionTaskStates?.[id]?.status ?? "open";
const unique = <T,>(items: T[]) => [...new Set(items)];

export function collectionPrefill(params: { get: (name: string) => string | null }): { taskId: string; context: Context } | null {
  if (params.get("collect") !== "1") return null; const taskId = params.get("task"); const country = params.get("country"); const commodity = params.get("commodity"); const stage = params.get("stage"); if (!taskId || (country !== "FJ" && country !== "AU") || !["tomatoes", "bananas", "taro"].includes(commodity ?? "") || !["handling", "storage", "transport"].includes(stage ?? "")) return null;
  return { taskId, context: { country, commodity: commodity as Context["commodity"], stage: stage as Context["stage"], date: new Date().toISOString().slice(0, 10), location: params.get("region") ?? "" } };
}

function collectTask(state: StoredState, cell: ReadinessCell, region: string | null, gaps: EvidenceGap[]): CollectionTask {
  const id = `collect:${cell.requirement.id}:${region ?? "all"}`; const usable = cell.accepted.length; const pendingPhoto = state.photoSources.flatMap((source) => (source.pendingCandidates ?? []).filter((candidate) => candidate.draft.context.country === cell.requirement.country && candidate.draft.context.commodity === cell.requirement.commodity && candidate.draft.context.stage === cell.requirement.stage).map((candidate) => ({ id: candidate.draft.id, sourceId: `photo:${source.id}` }))); const recoverableIds = unique([...gaps.filter((gap) => ["quality-blocker", "missing-field", "source-confidence"].includes(gap.type)).flatMap((gap) => gap.supportingRecordIds), ...pendingPhoto.map((item) => item.id)]); const blockedPotential = recoverableIds.length; const remaining = Math.max(0, cell.requirement.targetObservations - usable); const remainingAfterPotential = Math.max(0, remaining - blockedPotential); const satisfied = cell.status === "satisfied" && !region;
  const targetText = region ? ` in ${region}` : ""; const label = `${commodityName[cell.requirement.commodity]} ${cell.requirement.stage}${targetText}`;
  return { id, category: "collect", status: taskState(state, id, satisfied), priority: priority(cell.requirement.priorityWeight, cell.status === "missing"), country: cell.requirement.country, commodity: cell.requirement.commodity, stage: cell.requirement.stage, region, requirementId: cell.requirement.id, target: cell.requirement.targetObservations, usable, blockedPotential, remaining, remainingAfterPotential, title: satisfied ? `${label} requirement satisfied` : `Collect ${Math.max(1, remainingAfterPotential || remaining)} additional ${label} observation${Math.max(1, remainingAfterPotential || remaining) === 1 ? "" : "s"}`, explanation: satisfied ? `Configured target of ${cell.requirement.targetObservations} usable observations is currently met.` : blockedPotential ? `${usable}/${cell.requirement.targetObservations} usable. ${blockedPotential} existing record${blockedPotential === 1 ? " may" : "s may"} be recoverable first; after review, ${remainingAfterPotential} additional observation${remainingAfterPotential === 1 ? "" : "s"} may still be needed.` : `${usable}/${cell.requirement.targetObservations} usable observations. ${remaining} remaining configured collection requirement${remaining === 1 ? "" : "s"}.`, recordIds: unique([...cell.accepted.map((record) => record.id), ...recoverableIds]), issueIds: unique(gaps.flatMap((gap) => gap.blockingIssueIds)), sourceIds: unique([...cell.sourceIds, ...gaps.flatMap((gap) => gap.sourceIds), ...pendingPhoto.map((item) => item.sourceId)]), actionHref: `/?collect=1&task=${encodeURIComponent(id)}&country=${cell.requirement.country}&commodity=${cell.requirement.commodity}&stage=${cell.requirement.stage}${region ? `&region=${encodeURIComponent(region)}` : ""}`, actionLabel: "Collect observation" };
}

function reviewTasks(state: StoredState, cell: ReadinessCell, gaps: EvidenceGap[]): CollectionTask[] {
  const relevant = gaps.filter((gap) => ["quality-blocker", "missing-field", "source-confidence", "fragmentation"].includes(gap.type) && gap.supportingRecordIds.length);
  const groups = new Map<string, EvidenceGap[]>(); relevant.forEach((gap) => { const key = gap.type === "missing-field" && gap.title.includes("crate conversion") ? "crate-conversion" : gap.type; groups.set(key, [...(groups.get(key) ?? []), gap]); });
  return [...groups.entries()].map(([kind, group]) => { const recordIds = unique(group.flatMap((gap) => gap.supportingRecordIds)); const sourceIds = unique(group.flatMap((gap) => gap.sourceIds)); const issueIds = unique(group.flatMap((gap) => gap.blockingIssueIds)); const photoSource = sourceIds.find((id) => id.startsWith("photo:")); const importSource = sourceIds.find((id) => id.startsWith("import:")); const id = `review:${cell.requirement.id}:${kind}`; const label = `${commodityName[cell.requirement.commodity]} ${cell.requirement.stage}`; const title = kind === "crate-conversion" ? `Add crate conversion for ${recordIds.length} ${label} record${recordIds.length === 1 ? "" : "s"}` : kind === "source-confidence" ? `Review ${recordIds.length} ${label} extracted record${recordIds.length === 1 ? "" : "s"}` : kind === "missing-field" ? `Complete ${recordIds.length} ${label} imported record${recordIds.length === 1 ? "" : "s"}` : `Review ${recordIds.length} blocked ${label} record${recordIds.length === 1 ? "" : "s"}`;
    const actionHref = photoSource ? `/datasets/photo?source=${encodeURIComponent(photoSource.slice("photo:".length))}` : importSource ? `/datasets/${encodeURIComponent(importSource.slice("import:".length))}/map?review=needs-information` : "/quality";
    const actionLabel = photoSource ? "Review photo evidence" : importSource ? "Review imported records" : "Review records";
    return { id, category: "review", status: taskState(state, id), priority: group.some((gap) => gap.severity === "high") ? "high" : group.some((gap) => gap.severity === "medium") ? "medium" : "low", country: cell.requirement.country, commodity: cell.requirement.commodity, stage: cell.requirement.stage, region: null, requirementId: cell.requirement.id, target: cell.requirement.targetObservations, usable: cell.accepted.length, blockedPotential: recordIds.length, remaining: Math.max(0, cell.requirement.targetObservations - cell.accepted.length), remainingAfterPotential: Math.max(0, cell.requirement.targetObservations - cell.accepted.length - recordIds.length), title, explanation: `Configured requirement: ${cell.requirement.targetObservations} usable ${label} observations. ${cell.accepted.length} are usable; ${recordIds.length} existing record${recordIds.length === 1 ? " may" : "s may"} satisfy the requirement after review. ${group.map((gap) => gap.explanation).join(" ")}`, recordIds, issueIds, sourceIds, actionHref, actionLabel };
  });
}

export function getCollectionTasks(state: StoredState, country: Country): CollectionTask[] {
  const readiness = evaluateReadiness(state, country); const gaps = detectEvidenceGaps(state, country).gaps; const tasks: CollectionTask[] = [];
  readiness.cells.forEach((cell) => { const related = gaps.filter((gap) => gap.requirementId === cell.requirement.id); tasks.push(...reviewTasks(state, cell, related)); if (cell.missingRegions.length) cell.missingRegions.forEach((region) => tasks.push(collectTask(state, cell, region, related))); else tasks.push(collectTask(state, cell, null, related)); });
  state.photoSources.forEach((source) => (source.pendingCandidates ?? []).forEach((candidate) => { const cell = readiness.cells.find((item) => item.requirement.commodity === candidate.draft.context.commodity && item.requirement.stage === candidate.draft.context.stage && item.requirement.country === candidate.draft.context.country); if (!cell) return; const id = `review:photo:${source.id}:${candidate.index}`; const label = `${commodityName[cell.requirement.commodity]} ${cell.requirement.stage}`; tasks.push({ id, category: "review", status: taskState(state, id), priority: priority(cell.requirement.priorityWeight, candidate.unresolved.length > 0), country, commodity: cell.requirement.commodity, stage: cell.requirement.stage, region: null, requirementId: cell.requirement.id, target: cell.requirement.targetObservations, usable: cell.accepted.length, blockedPotential: 1, remaining: Math.max(0, cell.requirement.targetObservations - cell.accepted.length), remainingAfterPotential: Math.max(0, cell.requirement.targetObservations - cell.accepted.length - 1), title: `Review photographed ${label} observation`, explanation: `This photographed observation is still awaiting human review${candidate.unresolved.length ? `: ${candidate.unresolved.join(", ")} unresolved` : ""}. It may satisfy the configured requirement after deterministic validation.`, recordIds: [candidate.draft.id], issueIds: [], sourceIds: [`photo:${source.id}`], actionHref: `/datasets/photo?source=${encodeURIComponent(source.id)}`, actionLabel: "Review photo evidence" }); }));
  const rank = { high: 3, medium: 2, low: 1 }; return tasks.sort((a, b) => (a.category === b.category ? 0 : a.category === "review" ? -1 : 1) || rank[b.priority] - rank[a.priority] || a.title.localeCompare(b.title));
}

export function collectionPlanCsv(tasks: CollectionTask[]) {
  const quote = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
  return [["task type", "country", "commodity", "stage", "region", "priority", "target", "usable", "blocked potential", "remaining", "status"], ...tasks.map((task) => [task.category, task.country, task.commodity, task.stage, task.region ?? "", task.priority, task.target, task.usable, task.blockedPotential, task.remainingAfterPotential, task.status])].map((row) => row.map(quote).join(",")).join("\n");
}
