import { detectDataQualityIssues } from "./quality";
import { evaluateReadiness, type ReadinessCell } from "./readiness";
import type { Country, EvidenceGap, EvidenceGapType, ReadinessCommodity, StoredState } from "./types";

const names: Record<ReadinessCommodity, string> = { tomatoes: "Tomato", bananas: "Banana", taro: "Taro", coconut: "Coconut", tuna: "Tuna" };
const severityValue = { high: 3, medium: 2, low: 1 } as const;
const prioritySeverity = (weight: 1 | 2 | 3, strong = false): EvidenceGap["severity"] => strong || weight === 3 ? "high" : weight === 2 ? "medium" : "low";
const fieldLabel = (field: string) => ({ destination: "Destination", incomingAmount: "Incoming quantity", incomingUnit: "Incoming quantity unit", affectedAmount: "Affected quantity", affectedUnit: "Affected quantity unit", measurement: "Measurement method", region: "Region", location: "Location" }[field] ?? field);
const unique = <T,>(items: T[]) => [...new Set(items)];

export type EvidenceGapSummary = { country: Country; gaps: EvidenceGap[]; majorGapCount: number; missingRequirementCount: number; missingRegionCount: number; blockedRecordCount: number; baselineGapCount: number; recoverableRecordCount: number };

function gap(cell: ReadinessCell, type: EvidenceGapType, severity: EvidenceGap["severity"], title: string, explanation: string, options: Partial<Pick<EvidenceGap, "region" | "supportingRecordIds" | "blockingIssueIds" | "sourceIds">> & { field?: string } = {}): EvidenceGap {
  return { id: `${cell.requirement.id}:${type}:${options.region ?? "all"}:${options.blockingIssueIds?.slice().sort().join(",") ?? ""}${options.field ? `:${options.field}` : ""}`, country: cell.requirement.country, commodity: cell.requirement.commodity, stage: cell.requirement.stage, region: options.region ?? null, type, severity, title, explanation, requirementId: cell.requirement.id, supportingRecordIds: options.supportingRecordIds ?? [], blockingIssueIds: options.blockingIssueIds ?? [], sourceIds: options.sourceIds ?? cell.sourceIds, priorityWeight: cell.requirement.priorityWeight };
}

export function detectEvidenceGaps(state: StoredState, country: Country): EvidenceGapSummary {
  const readiness = evaluateReadiness(state, country); const issues = detectDataQualityIssues(state).filter((issue) => issue.status === "open"); const gaps: EvidenceGap[] = [];
  for (const cell of readiness.cells) {
    const records = [...cell.usable, ...cell.partial, ...cell.blocked, ...cell.excluded]; const recordIds = records.map((record) => record.id); const cellIssues = issues.filter((issue) => issue.recordIds.some((id) => recordIds.includes(id)));
    const label = `${names[cell.requirement.commodity]} → ${cell.requirement.stage === "handling" ? "post-harvest handling" : cell.requirement.stage}`;
    if (cell.status === "missing") gaps.push(gap(cell, "missing-data", prioritySeverity(cell.requirement.priorityWeight), `${label} evidence missing`, `0 usable observations satisfy the configured requirement of ${cell.requirement.targetObservations}.`, { supportingRecordIds: recordIds }));
    if (cell.status === "blocked" || cell.blocked.length) {
      const blockerIssues = cellIssues.filter((issue) => issue.severity === "error");
      gaps.push(gap(cell, "quality-blocker", prioritySeverity(cell.requirement.priorityWeight, cell.status === "blocked"), `${label} records are blocked`, `${cell.blocked.length} matching record${cell.blocked.length === 1 ? " is" : "s are"} blocked by unresolved deterministic validation or quality checks.`, { supportingRecordIds: cell.blocked.map((record) => record.id), blockingIssueIds: blockerIssues.map((issue) => issue.id) }));
    }
    for (const region of cell.missingRegions) gaps.push(gap(cell, "geographic-coverage", prioritySeverity(cell.requirement.priorityWeight), `${label} has no ${region} coverage`, `Evidence exists, but no usable or warning-level observation represents the configured ${region} requirement.`, { region, supportingRecordIds: [...cell.usable, ...cell.partial].map((record) => record.id) }));
    if (cell.requirement.baselineRequired && !cell.baselinePresent) gaps.push(gap(cell, "baseline", prioritySeverity(cell.requirement.priorityWeight), `${label} baseline evidence missing`, "Current or other evidence may exist, but the configured baseline period is not represented.", { supportingRecordIds: [...cell.usable, ...cell.partial].map((record) => record.id) }));
    const incompatible = cell.usable.filter((record) => !cell.requirement.acceptedMeasurementMethods.includes((record.measurement ?? "unknown") as "weighed" | "estimated" | "unknown"));
    if (incompatible.length) gaps.push(gap(cell, "measurement-method", prioritySeverity(cell.requirement.priorityWeight), `${label} uses an unaccepted measurement method`, `${incompatible.length} otherwise usable record${incompatible.length === 1 ? " uses" : "s use"} a measurement method outside the configured requirement.`, { supportingRecordIds: incompatible.map((record) => record.id) }));
    if (cell.status === "partial" && cell.accepted.length < cell.requirement.targetObservations) gaps.push(gap(cell, "missing-data", prioritySeverity(cell.requirement.priorityWeight), `Additional ${label} coverage required`, `${cell.accepted.length}/${cell.requirement.targetObservations} clean observations meet the configured collection requirement.`, { supportingRecordIds: cell.accepted.map((record) => record.id) }));
    const confidenceIssues = cellIssues.filter((issue) => issue.category === "source-confidence");
    if (confidenceIssues.length) gaps.push(gap(cell, "source-confidence", "medium", `${label} source extraction needs review`, `${unique(confidenceIssues.flatMap((issue) => issue.recordIds)).length} record${unique(confidenceIssues.flatMap((issue) => issue.recordIds)).length === 1 ? " has" : "s have"} low-confidence extracted critical fields that have not been human-confirmed.`, { supportingRecordIds: unique(confidenceIssues.flatMap((issue) => issue.recordIds)), blockingIssueIds: confidenceIssues.map((issue) => issue.id) }));
    const conversionIssues = cellIssues.filter((issue) => issue.category === "conversion");
    if (conversionIssues.length) gaps.push(gap(cell, "missing-field", "high", `${label} needs crate conversion`, "Affected quantities are recorded in crates without an officer-provided kilograms-per-crate conversion.", { supportingRecordIds: unique(conversionIssues.flatMap((issue) => issue.recordIds)), blockingIssueIds: conversionIssues.map((issue) => issue.id) }));
    const fragmentationIssues = cellIssues.filter((issue) => issue.category === "definition" || issue.category === "conflict");
    if (fragmentationIssues.length) gaps.push(gap(cell, "fragmentation", prioritySeverity(cell.requirement.priorityWeight), `${label} evidence cannot yet be combined`, `${fragmentationIssues.length} unresolved definition or value conflict${fragmentationIssues.length === 1 ? " prevents" : "s prevent"} transparent aggregation across sources.`, { supportingRecordIds: unique(fragmentationIssues.flatMap((issue) => issue.recordIds)), blockingIssueIds: fragmentationIssues.map((issue) => issue.id) }));
    const candidates = state.imports.flatMap((batch) => batch.candidates).filter((candidate) => recordIds.includes(candidate.id));
    const missingFields = unique(candidates.flatMap((candidate) => [...candidate.unresolvedFields, ...candidate.validationIssues.filter((issue) => issue.kind === "missing").map((issue) => issue.field)]).filter((field) => ["destination", "incomingAmount", "incomingUnit", "affectedAmount", "affectedUnit", "measurement", "region", "location"].includes(field)));
    for (const field of missingFields) { const affected = candidates.filter((candidate) => candidate.unresolvedFields.includes(field as never) || candidate.validationIssues.some((issue) => issue.kind === "missing" && issue.field === field)); gaps.push(gap(cell, "missing-field", ["destination", "incomingAmount", "affectedAmount"].includes(field) ? "high" : "medium", `${fieldLabel(field)} is missing in ${label} evidence`, `${affected.length} imported candidate row${affected.length === 1 ? " requires" : "s require"} ${fieldLabel(field).toLowerCase()} before it can support this requirement.`, { field, supportingRecordIds: affected.map((candidate) => candidate.id) })); }
  }
  const photoGaps = state.photoSources.filter((source) => { const sourceCountry = source.country?.trim().toLowerCase(); return (country === "FJ" && sourceCountry === "fiji") || (country === "AU" && sourceCountry === "australia"); }).filter((source) => source.detectedCount > source.confirmedRecordIds.length).map((source): EvidenceGap => ({ id: `photo-review:${source.id}`, country, commodity: null, stage: null, region: source.location, type: "source-confidence", severity: "medium", title: `${source.sourceName || source.originalFilename} needs review`, explanation: `${source.detectedCount - source.confirmedRecordIds.length} extracted photo observation${source.detectedCount - source.confirmedRecordIds.length === 1 ? " remains" : "s remain"} unconfirmed. They are recoverable evidence, not counted readiness evidence.`, requirementId: null, supportingRecordIds: source.confirmedRecordIds, blockingIssueIds: [], sourceIds: [`photo:${source.id}`], priorityWeight: 1 }));
  gaps.push(...photoGaps);
  gaps.sort((a, b) => severityValue[b.severity] - severityValue[a.severity] || b.priorityWeight - a.priorityWeight || a.title.localeCompare(b.title));
  return { country, gaps, majorGapCount: gaps.filter((item) => item.severity === "high").length, missingRequirementCount: gaps.filter((item) => item.type === "missing-data" && item.title.endsWith("evidence missing")).length, missingRegionCount: gaps.filter((item) => item.type === "geographic-coverage").length, blockedRecordCount: unique(gaps.filter((item) => item.type === "quality-blocker").flatMap((item) => item.supportingRecordIds)).length, baselineGapCount: gaps.filter((item) => item.type === "baseline").length, recoverableRecordCount: unique(gaps.filter((item) => item.type === "source-confidence" || item.type === "missing-field").flatMap((item) => item.supportingRecordIds)).length };
}
