import { z } from "zod";

export const countrySchema = z.enum(["AU", "FJ"]);
export const commoditySchema = z.enum(["tomatoes", "bananas", "taro"]);
export const stageSchema = z.enum(["handling", "storage", "transport"]);
export const destinationSchema = z.enum(["discarded", "composted", "donated", "resold", "animal_feed", "productive_use", "unknown"]);
export const measurementSchema = z.enum(["weighed", "estimated", "unknown"]);
export const quantitySchema = z.strictObject({ amount: z.number().nullable(), unit: z.enum(["kg", "g", "tonnes", "crates", "unknown"]), kgPerCrate: z.number().nullable() });
export const allocationSchema = z.strictObject({ destination: destinationSchema, quantity: quantitySchema });
export const contextSchema = z.strictObject({ country: countrySchema, commodity: commoditySchema, stage: stageSchema, date: z.iso.date(), location: z.string().max(200) });
const detectedSchema = z.strictObject({ country: countrySchema.nullable(), commodity: commoditySchema.nullable(), stage: stageSchema.nullable() });
export const extractionSchema = z.strictObject({
  incoming: quantitySchema.nullable(), affected: quantitySchema.nullable(), allocations: z.array(allocationSchema), cause: z.string().nullable(), measurement: measurementSchema,
  detectedContext: detectedSchema,
  evidence: z.strictObject({ incoming: z.string().nullable(), affected: z.string().nullable(), cause: z.string().nullable(), allocations: z.string().nullable(), commodity: z.string().nullable(), stage: z.string().nullable() }),
});
const evidenceSchema = z.strictObject({ incoming: z.string().optional(), affected: z.string().optional(), cause: z.string().optional(), allocations: z.string().optional(), commodity: z.string().optional(), stage: z.string().optional() });
export const draftSchema = z.strictObject({ id: z.string(), context: contextSchema, transcript: z.string(), incoming: quantitySchema, affected: quantitySchema, allocations: z.array(allocationSchema), cause: z.string().nullable(), measurement: measurementSchema, evidence: evidenceSchema, detectedContext: detectedSchema, acknowledgedConflicts: z.array(z.string()) });
const issueSchema = z.strictObject({ field: z.string(), message: z.string(), kind: z.enum(["missing", "invalid", "conflict"]) });
const dataSourceSchema = z.strictObject({ id: z.string(), name: z.string(), organisation: z.string().nullable(), country: z.string().nullable(), reportingYear: z.number().int().nullable(), sourceType: z.enum(["field-observation", "ministry-survey", "statistics-survey", "flapp", "ngo-project", "research", "administrative", "spreadsheet", "photo-scan", "other"]), inputFormat: z.enum(["voice", "manual-text", "csv", "xlsx", "image", "pdf", "legacy"]), originalFilename: z.string().nullable(), sheetName: z.string().nullable(), importedAt: z.iso.datetime(), notes: z.string().nullable(), archivedAt: z.iso.datetime().nullable() });
const fieldProvenanceSchema = z.strictObject({ field: z.string(), sourceField: z.string().nullable(), originalValue: z.unknown(), normalizedValue: z.unknown(), transformation: z.string().nullable(), aiConfidence: z.number().min(0).max(1).nullable(), mappingMethod: z.enum(["ai-suggested-human-confirmed", "manual", "ai-extraction", "direct"]).nullable(), manuallyCorrected: z.boolean(), correctedAt: z.iso.datetime().nullable(), evidence: z.string().nullable() });
const fieldChangeSchema = z.strictObject({ field: z.string(), previousValue: z.unknown(), newValue: z.unknown(), timestamp: z.iso.datetime(), origin: z.enum(["ai-extraction", "ai-mapping", "normalization", "user", "validation-resolution", "migration"]), reason: z.string().nullable() });
const sourceReferenceSchema = z.strictObject({ importBatchId: z.string().nullable(), originalFilename: z.string().nullable(), sheetName: z.string().nullable(), rowNumber: z.number().int().positive().nullable(), rawRowReference: z.string().nullable(), imageId: z.string().nullable(), extractedObservationIndex: z.number().int().nonnegative().nullable(), extractionTimestamp: z.iso.datetime().nullable(), extractionMethod: z.string().nullable(), transcriptionMethod: z.string().nullable() });
const recordProvenanceSchema = z.strictObject({ id: z.string(), sourceId: z.string(), origin: z.enum(["voice", "manual-text", "spreadsheet", "photo-scan", "legacy"]), inputFormat: z.enum(["voice", "manual-text", "csv", "xlsx", "image", "pdf", "legacy"]), source: sourceReferenceSchema, fields: z.array(fieldProvenanceSchema), audit: z.array(fieldChangeSchema), validation: z.strictObject({ status: z.enum(["passed", "needs-review", "legacy-unknown"]), evaluatedAt: z.iso.datetime().nullable(), issueCount: z.number().int().nonnegative(), issues: z.array(issueSchema) }), reviewedAt: z.iso.datetime().nullable() });
export const recordSchema = z.strictObject({
  id: z.string(), context: contextSchema, transcript: z.string(), incomingKg: z.number().positive(), affectedKg: z.number().nonnegative(),
  allocations: z.array(z.strictObject({ destination: destinationSchema, kg: z.number().nonnegative() })), lossKg: z.number().nonnegative(), lossPercent: z.number().min(0).max(100),
  cause: z.string().nullable(), measurement: measurementSchema, evidence: evidenceSchema, provenance: recordProvenanceSchema.nullable().default(null), confirmedAt: z.iso.datetime(), isSample: z.boolean(),
});
export const trialSchema = z.strictObject({ id: z.string(), scenarioId: z.string(), mode: z.enum(["manual", "assisted"]), inputMethod: z.enum(["voice", "text", "manual"]), elapsedMs: z.number().nonnegative(), correct: z.boolean(), errors: z.array(z.string()), completedAt: z.iso.datetime() });
const importCellSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
const importColumnSchema = z.strictObject({ id: z.string(), label: z.string(), originalLabel: z.string(), sourceIndex: z.number().int().nonnegative() });
const importWarningSchema = z.strictObject({ code: z.string(), message: z.string(), rowNumber: z.number().int().positive().optional() });
const importedRawRowSchema = z.strictObject({ sourceRowNumber: z.number().int().positive(), values: z.record(z.string(), importCellSchema) });
const canonicalFieldSchema = z.enum(["commodity", "foodGroup", "country", "region", "location", "observationDate", "reportingYear", "stage", "incomingAmount", "incomingUnit", "affectedAmount", "affectedUnit", "destination", "cause", "measurement", "notes", "sourceGeography", "samplingStratum", "periodFlag"]);
const mappingTargetSchema = z.union([canonicalFieldSchema, z.literal("ignored"), z.literal("unmapped")]);
const mappingMethodSchema = z.enum(["ai-suggested-human-confirmed", "manual"]);
const columnMappingSchema = z.strictObject({ sourceColumnId: z.string(), target: mappingTargetSchema, confidence: z.number().min(0).max(1).nullable(), reasoning: z.string().max(500).nullable(), suggestedTransformation: z.string().max(200).nullable(), method: mappingMethodSchema.nullable() });
const mappingPlanSchema = z.strictObject({ mappings: z.array(columnMappingSchema), defaults: z.strictObject({ applyDatasetCountry: z.boolean(), applyReportingYear: z.boolean() }), confirmedAt: z.iso.datetime(), method: mappingMethodSchema });
const transformationAuditSchema = z.strictObject({ sourceColumnId: z.string().nullable(), sourceLabel: z.string(), originalValue: importCellSchema, normalizedValue: importCellSchema, transformation: z.string(), source: z.enum(["row", "dataset-metadata"]) });
const candidateValuesSchema = z.strictObject({
  commodity: commoditySchema.nullable(), foodGroup: z.string().nullable(), country: countrySchema.nullable(), region: z.string().nullable(), location: z.string().nullable(), observationDate: z.string().nullable(), reportingYear: z.number().int().nullable(), stage: stageSchema.nullable(),
  incoming: quantitySchema, affected: quantitySchema, destination: destinationSchema.nullable(), cause: z.string().nullable(), measurement: measurementSchema.nullable(), notes: z.string().nullable(), sourceGeography: z.string().nullable(), samplingStratum: z.string().nullable(), periodFlag: z.string().nullable(),
});
const candidateSchema = z.strictObject({ id: z.string(), sourceRowNumber: z.number().int().positive(), values: candidateValuesSchema, provenance: z.partialRecord(canonicalFieldSchema, transformationAuditSchema), trace: recordProvenanceSchema.nullable().default(null), unresolvedFields: z.array(canonicalFieldSchema), validationIssues: z.array(issueSchema), validationStatus: z.enum(["ready-for-review", "needs-information"]), mappingStatus: z.literal("candidate") });
export const importBatchSchema = z.strictObject({
  id: z.string(), datasetName: z.string().min(1).max(200), originalFilename: z.string().min(1), fileType: z.enum(["csv", "xlsx", "xls"]), sheetName: z.string().nullable(),
  organisation: z.string().max(200).nullable(), country: z.string().max(100).nullable(), reportingYear: z.number().int().min(1000).max(9999).nullable(), sourceType: z.enum(["ministry_survey", "national_statistics_survey", "fao_flapp", "ngo_project", "research_study", "administrative_data", "fieldloss_export", "other"]), notes: z.string().max(2000).nullable(),
  importedAt: z.iso.datetime(), headers: z.array(importColumnSchema).min(1), rawRows: z.array(importedRawRowSchema), status: z.enum(["uploaded", "mapping-required", "mapped", "validation-required", "ready"]), parseWarnings: z.array(importWarningSchema), mapping: mappingPlanSchema.nullable().default(null), candidates: z.array(candidateSchema).default([]),
});
export const schemaMappingRequestSchema = z.strictObject({ dataset: z.strictObject({ datasetName: z.string().max(200), organisation: z.string().nullable(), country: z.string().nullable(), reportingYear: z.number().int().nullable(), sourceType: z.string(), notes: z.string().nullable() }), headers: z.array(z.strictObject({ id: z.string(), label: z.string() })).min(1), sampleRows: z.array(z.record(z.string(), importCellSchema)).max(10) });
export const schemaMappingResponseSchema = z.strictObject({ mappings: z.array(z.strictObject({ sourceColumnId: z.string(), target: z.union([canonicalFieldSchema, z.literal("ignored")]), confidence: z.number().min(0).max(1), reasoning: z.string().max(500), suggestedTransformation: z.string().max(200).nullable() })) });
const photoObservationSchema = z.strictObject({ commodity: commoditySchema.nullable(), country: countrySchema.nullable(), region: z.string().nullable(), location: z.string().nullable(), date: z.string().nullable(), stage: stageSchema.nullable(), incoming: quantitySchema.nullable(), affected: quantitySchema.nullable(), allocations: z.array(z.strictObject({ destination: destinationSchema.nullable(), quantity: quantitySchema })), cause: z.string().nullable(), measurement: measurementSchema.nullable(), notes: z.string().nullable(), confidenceByField: z.record(z.string(), z.number().min(0).max(1)), unresolvedFields: z.array(z.string()) });
export const documentExtractionSchema = z.strictObject({ observations: z.array(photoObservationSchema).max(30), documentWarnings: z.array(z.string().max(500)) });
const photoCandidateSchema = z.strictObject({ draft: draftSchema, original: draftSchema, index: z.number().int().nonnegative(), confidence: z.record(z.string(), z.number().min(0).max(1)), unresolved: z.array(z.string()) });
const photoSourceSchema = z.strictObject({ id: z.string(), imageId: z.string(), originalFilename: z.string(), mimeType: z.string(), sourceName: z.string().nullable(), organisation: z.string().nullable(), country: z.string().nullable(), reportingYear: z.number().int().nullable(), location: z.string().nullable(), sourceType: z.enum(["ministry_survey", "national_statistics_survey", "fao_flapp", "ngo_project", "research_study", "administrative_data", "fieldloss_export", "other"]), importedAt: z.iso.datetime(), extractedAt: z.iso.datetime().nullable(), extractionMethod: z.enum(["openai-vision", "manual-from-photo"]).nullable(), detectedCount: z.number().int().nonnegative(), confirmedRecordIds: z.array(z.string()), documentWarnings: z.array(z.string()), pendingCandidates: z.array(photoCandidateSchema).default([]) });
const qualityIssueStateSchema = z.strictObject({ status: z.enum(["open", "resolved", "accepted"]), updatedAt: z.iso.datetime() });
const readinessRequirementSchema = z.strictObject({ id: z.string(), country: countrySchema, commodity: z.enum(["tomatoes", "bananas", "taro", "coconut", "tuna"]), stage: stageSchema, requiredRegions: z.array(z.string()), targetObservations: z.number().int().positive(), acceptedMeasurementMethods: z.array(measurementSchema), baselineRequired: z.boolean(), priorityWeight: z.union([z.literal(1), z.literal(2), z.literal(3)]) });
const compilationCommoditySchema = z.strictObject({ id: z.string(), commodity: z.enum(["tomatoes", "bananas", "taro", "coconut", "tuna"]), foodGroup: z.string().nullable(), productionWeight: z.number().nonnegative().nullable() });
const draftCompilationSchema = z.strictObject({ config: z.strictObject({ country: countrySchema, baselineYear: z.number().int().min(1900).max(9999).nullable(), currentYear: z.number().int().min(1900).max(9999).nullable(), commodityBasket: z.array(compilationCommoditySchema), aggregationMethod: z.enum(["weighted-production", "unweighted-demonstration"]) }), approvals: z.array(z.strictObject({ commodity: z.enum(["tomatoes", "bananas", "taro", "coconut", "tuna"]), estimate: z.number().finite(), baselineEstimate: z.number().finite().nullable(), method: z.string(), evidenceSourceIds: z.array(z.string()), recordIds: z.array(z.string()), approvedAt: z.iso.datetime(), action: z.literal("approved-for-draft-compilation") })) });
// `imports` defaults to an empty list so state written before dataset import remains readable.
export const stateSchema = z.strictObject({ schemaVersion: z.literal(1), draft: draftSchema.nullable(), records: z.array(recordSchema), trials: z.array(trialSchema), imports: z.array(importBatchSchema).default([]), photoSources: z.array(photoSourceSchema).default([]), sources: z.array(dataSourceSchema).default([]), qualityIssueStates: z.record(z.string(), qualityIssueStateSchema).default({}), duplicateExcludedRecordIds: z.array(z.string()).default([]), readinessRequirements: z.array(readinessRequirementSchema).default([]), collectionTaskStates: z.record(z.string(), z.strictObject({ status: z.enum(["in-progress", "dismissed"]), updatedAt: z.iso.datetime() })).default({}), draftCompilation: draftCompilationSchema.optional() });
export const extractionRequestSchema = z.strictObject({ transcript: z.string().trim().min(1).max(8000), context: contextSchema });
